# Site settings
title: "Frontloops solutions"
description: "Frontloops challenges solutions."
baseurl: "/frontloops"
url: "https://glascode.github.io"  # absolute url

# Build settings
kramdown:
  input: GFM
